on:
  #push:
  schedule:
    - cron: '30 18 * * *' # run at 6pm UTC
    - cron: '30 14 * * *' # run at 2pm UTC
    - cron: '30 10 * * *' # run at 10am UTC
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Europe/Berlin
    - name: Create local changes
      run: . ./download_all.sh
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master'
